// SISTEMA.v

// Generated using ACDS version 17.0 595

`timescale 1 ps / 1 ps
module SISTEMA (
		input  wire  clk_clk,                     //                    clk.clk
		output wire  ldr_external_interface_sclk, // ldr_external_interface.sclk
		output wire  ldr_external_interface_cs_n, //                       .cs_n
		input  wire  ldr_external_interface_dout, //                       .dout
		output wire  ldr_external_interface_din,  //                       .din
		input  wire  reset_reset_n                //                  reset.reset_n
	);

	wire   [31:0] procesador1_data_master_readdata;                          // mm_interconnect_0:Procesador1_data_master_readdata -> Procesador1:d_readdata
	wire          procesador1_data_master_waitrequest;                       // mm_interconnect_0:Procesador1_data_master_waitrequest -> Procesador1:d_waitrequest
	wire          procesador1_data_master_debugaccess;                       // Procesador1:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:Procesador1_data_master_debugaccess
	wire   [18:0] procesador1_data_master_address;                           // Procesador1:d_address -> mm_interconnect_0:Procesador1_data_master_address
	wire    [3:0] procesador1_data_master_byteenable;                        // Procesador1:d_byteenable -> mm_interconnect_0:Procesador1_data_master_byteenable
	wire          procesador1_data_master_read;                              // Procesador1:d_read -> mm_interconnect_0:Procesador1_data_master_read
	wire          procesador1_data_master_readdatavalid;                     // mm_interconnect_0:Procesador1_data_master_readdatavalid -> Procesador1:d_readdatavalid
	wire          procesador1_data_master_write;                             // Procesador1:d_write -> mm_interconnect_0:Procesador1_data_master_write
	wire   [31:0] procesador1_data_master_writedata;                         // Procesador1:d_writedata -> mm_interconnect_0:Procesador1_data_master_writedata
	wire   [31:0] procesador1_instruction_master_readdata;                   // mm_interconnect_0:Procesador1_instruction_master_readdata -> Procesador1:i_readdata
	wire          procesador1_instruction_master_waitrequest;                // mm_interconnect_0:Procesador1_instruction_master_waitrequest -> Procesador1:i_waitrequest
	wire   [18:0] procesador1_instruction_master_address;                    // Procesador1:i_address -> mm_interconnect_0:Procesador1_instruction_master_address
	wire          procesador1_instruction_master_read;                       // Procesador1:i_read -> mm_interconnect_0:Procesador1_instruction_master_read
	wire          procesador1_instruction_master_readdatavalid;              // mm_interconnect_0:Procesador1_instruction_master_readdatavalid -> Procesador1:i_readdatavalid
	wire   [31:0] mm_interconnect_0_ldr_adc_slave_readdata;                  // LDR:readdata -> mm_interconnect_0:LDR_adc_slave_readdata
	wire          mm_interconnect_0_ldr_adc_slave_waitrequest;               // LDR:waitrequest -> mm_interconnect_0:LDR_adc_slave_waitrequest
	wire    [2:0] mm_interconnect_0_ldr_adc_slave_address;                   // mm_interconnect_0:LDR_adc_slave_address -> LDR:address
	wire          mm_interconnect_0_ldr_adc_slave_read;                      // mm_interconnect_0:LDR_adc_slave_read -> LDR:read
	wire          mm_interconnect_0_ldr_adc_slave_write;                     // mm_interconnect_0:LDR_adc_slave_write -> LDR:write
	wire   [31:0] mm_interconnect_0_ldr_adc_slave_writedata;                 // mm_interconnect_0:LDR_adc_slave_writedata -> LDR:writedata
	wire          mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_chipselect -> JTAG_UART:av_chipselect
	wire   [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata;    // JTAG_UART:av_readdata -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_readdata
	wire          mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest; // JTAG_UART:av_waitrequest -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_waitrequest
	wire    [0:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_address;     // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_address -> JTAG_UART:av_address
	wire          mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;        // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_read -> JTAG_UART:av_read_n
	wire          mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;       // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_write -> JTAG_UART:av_write_n
	wire   [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata;   // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_writedata -> JTAG_UART:av_writedata
	wire   [31:0] mm_interconnect_0_procesador1_debug_mem_slave_readdata;    // Procesador1:debug_mem_slave_readdata -> mm_interconnect_0:Procesador1_debug_mem_slave_readdata
	wire          mm_interconnect_0_procesador1_debug_mem_slave_waitrequest; // Procesador1:debug_mem_slave_waitrequest -> mm_interconnect_0:Procesador1_debug_mem_slave_waitrequest
	wire          mm_interconnect_0_procesador1_debug_mem_slave_debugaccess; // mm_interconnect_0:Procesador1_debug_mem_slave_debugaccess -> Procesador1:debug_mem_slave_debugaccess
	wire    [8:0] mm_interconnect_0_procesador1_debug_mem_slave_address;     // mm_interconnect_0:Procesador1_debug_mem_slave_address -> Procesador1:debug_mem_slave_address
	wire          mm_interconnect_0_procesador1_debug_mem_slave_read;        // mm_interconnect_0:Procesador1_debug_mem_slave_read -> Procesador1:debug_mem_slave_read
	wire    [3:0] mm_interconnect_0_procesador1_debug_mem_slave_byteenable;  // mm_interconnect_0:Procesador1_debug_mem_slave_byteenable -> Procesador1:debug_mem_slave_byteenable
	wire          mm_interconnect_0_procesador1_debug_mem_slave_write;       // mm_interconnect_0:Procesador1_debug_mem_slave_write -> Procesador1:debug_mem_slave_write
	wire   [31:0] mm_interconnect_0_procesador1_debug_mem_slave_writedata;   // mm_interconnect_0:Procesador1_debug_mem_slave_writedata -> Procesador1:debug_mem_slave_writedata
	wire          mm_interconnect_0_timer_s1_chipselect;                     // mm_interconnect_0:TIMER_s1_chipselect -> TIMER:chipselect
	wire   [15:0] mm_interconnect_0_timer_s1_readdata;                       // TIMER:readdata -> mm_interconnect_0:TIMER_s1_readdata
	wire    [2:0] mm_interconnect_0_timer_s1_address;                        // mm_interconnect_0:TIMER_s1_address -> TIMER:address
	wire          mm_interconnect_0_timer_s1_write;                          // mm_interconnect_0:TIMER_s1_write -> TIMER:write_n
	wire   [15:0] mm_interconnect_0_timer_s1_writedata;                      // mm_interconnect_0:TIMER_s1_writedata -> TIMER:writedata
	wire          mm_interconnect_0_sram1_s1_chipselect;                     // mm_interconnect_0:SRAM1_s1_chipselect -> SRAM1:chipselect
	wire  [127:0] mm_interconnect_0_sram1_s1_readdata;                       // SRAM1:readdata -> mm_interconnect_0:SRAM1_s1_readdata
	wire   [12:0] mm_interconnect_0_sram1_s1_address;                        // mm_interconnect_0:SRAM1_s1_address -> SRAM1:address
	wire   [15:0] mm_interconnect_0_sram1_s1_byteenable;                     // mm_interconnect_0:SRAM1_s1_byteenable -> SRAM1:byteenable
	wire          mm_interconnect_0_sram1_s1_write;                          // mm_interconnect_0:SRAM1_s1_write -> SRAM1:write
	wire  [127:0] mm_interconnect_0_sram1_s1_writedata;                      // mm_interconnect_0:SRAM1_s1_writedata -> SRAM1:writedata
	wire          mm_interconnect_0_sram1_s1_clken;                          // mm_interconnect_0:SRAM1_s1_clken -> SRAM1:clken
	wire          irq_mapper_receiver0_irq;                                  // TIMER:irq -> irq_mapper:receiver0_irq
	wire          irq_mapper_receiver1_irq;                                  // JTAG_UART:av_irq -> irq_mapper:receiver1_irq
	wire   [31:0] procesador1_irq_irq;                                       // irq_mapper:sender_irq -> Procesador1:irq
	wire          rst_controller_reset_out_reset;                            // rst_controller:reset_out -> [JTAG_UART:rst_n, LDR:reset, Procesador1:reset_n, SRAM1:reset, TIMER:reset_n, irq_mapper:reset, mm_interconnect_0:Procesador1_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire          rst_controller_reset_out_reset_req;                        // rst_controller:reset_req -> [Procesador1:reset_req, SRAM1:reset_req, rst_translator:reset_req_in]
	wire          procesador1_debug_reset_request_reset;                     // Procesador1:debug_reset_request -> rst_controller:reset_in1

	SISTEMA_JTAG_UART jtag_uart (
		.clk            (clk_clk),                                                   //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                           //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver1_irq)                                   //               irq.irq
	);

	SISTEMA_LDR #(
		.board          ("DE1-SoC"),
		.board_rev      ("Autodetect"),
		.tsclk          (4),
		.numch          (3),
		.max10pllmultby (1),
		.max10plldivby  (1)
	) ldr (
		.clock       (clk_clk),                                     //                clk.clk
		.reset       (rst_controller_reset_out_reset),              //              reset.reset
		.write       (mm_interconnect_0_ldr_adc_slave_write),       //          adc_slave.write
		.readdata    (mm_interconnect_0_ldr_adc_slave_readdata),    //                   .readdata
		.writedata   (mm_interconnect_0_ldr_adc_slave_writedata),   //                   .writedata
		.address     (mm_interconnect_0_ldr_adc_slave_address),     //                   .address
		.waitrequest (mm_interconnect_0_ldr_adc_slave_waitrequest), //                   .waitrequest
		.read        (mm_interconnect_0_ldr_adc_slave_read),        //                   .read
		.adc_sclk    (ldr_external_interface_sclk),                 // external_interface.export
		.adc_cs_n    (ldr_external_interface_cs_n),                 //                   .export
		.adc_dout    (ldr_external_interface_dout),                 //                   .export
		.adc_din     (ldr_external_interface_din)                   //                   .export
	);

	SISTEMA_Procesador1 procesador1 (
		.clk                                 (clk_clk),                                                   //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                           //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                        //                          .reset_req
		.d_address                           (procesador1_data_master_address),                           //               data_master.address
		.d_byteenable                        (procesador1_data_master_byteenable),                        //                          .byteenable
		.d_read                              (procesador1_data_master_read),                              //                          .read
		.d_readdata                          (procesador1_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (procesador1_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (procesador1_data_master_write),                             //                          .write
		.d_writedata                         (procesador1_data_master_writedata),                         //                          .writedata
		.d_readdatavalid                     (procesador1_data_master_readdatavalid),                     //                          .readdatavalid
		.debug_mem_slave_debugaccess_to_roms (procesador1_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (procesador1_instruction_master_address),                    //        instruction_master.address
		.i_read                              (procesador1_instruction_master_read),                       //                          .read
		.i_readdata                          (procesador1_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (procesador1_instruction_master_waitrequest),                //                          .waitrequest
		.i_readdatavalid                     (procesador1_instruction_master_readdatavalid),              //                          .readdatavalid
		.irq                                 (procesador1_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (procesador1_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_procesador1_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_procesador1_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_procesador1_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_procesador1_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_procesador1_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_procesador1_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_procesador1_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_procesador1_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                           // custom_instruction_master.readra
	);

	SISTEMA_SRAM1 sram1 (
		.clk        (clk_clk),                               //   clk1.clk
		.address    (mm_interconnect_0_sram1_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_sram1_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_sram1_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_sram1_s1_write),      //       .write
		.readdata   (mm_interconnect_0_sram1_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_sram1_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_sram1_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),        // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),    //       .reset_req
		.freeze     (1'b0)                                   // (terminated)
	);

	SISTEMA_TIMER timer (
		.clk        (clk_clk),                               //   clk.clk
		.reset_n    (~rst_controller_reset_out_reset),       // reset.reset_n
		.address    (mm_interconnect_0_timer_s1_address),    //    s1.address
		.writedata  (mm_interconnect_0_timer_s1_writedata),  //      .writedata
		.readdata   (mm_interconnect_0_timer_s1_readdata),   //      .readdata
		.chipselect (mm_interconnect_0_timer_s1_chipselect), //      .chipselect
		.write_n    (~mm_interconnect_0_timer_s1_write),     //      .write_n
		.irq        (irq_mapper_receiver0_irq)               //   irq.irq
	);

	SISTEMA_mm_interconnect_0 mm_interconnect_0 (
		.CLOCK_50_clk_clk                              (clk_clk),                                                   //                            CLOCK_50_clk.clk
		.Procesador1_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                            // Procesador1_reset_reset_bridge_in_reset.reset
		.Procesador1_data_master_address               (procesador1_data_master_address),                           //                 Procesador1_data_master.address
		.Procesador1_data_master_waitrequest           (procesador1_data_master_waitrequest),                       //                                        .waitrequest
		.Procesador1_data_master_byteenable            (procesador1_data_master_byteenable),                        //                                        .byteenable
		.Procesador1_data_master_read                  (procesador1_data_master_read),                              //                                        .read
		.Procesador1_data_master_readdata              (procesador1_data_master_readdata),                          //                                        .readdata
		.Procesador1_data_master_readdatavalid         (procesador1_data_master_readdatavalid),                     //                                        .readdatavalid
		.Procesador1_data_master_write                 (procesador1_data_master_write),                             //                                        .write
		.Procesador1_data_master_writedata             (procesador1_data_master_writedata),                         //                                        .writedata
		.Procesador1_data_master_debugaccess           (procesador1_data_master_debugaccess),                       //                                        .debugaccess
		.Procesador1_instruction_master_address        (procesador1_instruction_master_address),                    //          Procesador1_instruction_master.address
		.Procesador1_instruction_master_waitrequest    (procesador1_instruction_master_waitrequest),                //                                        .waitrequest
		.Procesador1_instruction_master_read           (procesador1_instruction_master_read),                       //                                        .read
		.Procesador1_instruction_master_readdata       (procesador1_instruction_master_readdata),                   //                                        .readdata
		.Procesador1_instruction_master_readdatavalid  (procesador1_instruction_master_readdatavalid),              //                                        .readdatavalid
		.JTAG_UART_avalon_jtag_slave_address           (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //             JTAG_UART_avalon_jtag_slave.address
		.JTAG_UART_avalon_jtag_slave_write             (mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),       //                                        .write
		.JTAG_UART_avalon_jtag_slave_read              (mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),        //                                        .read
		.JTAG_UART_avalon_jtag_slave_readdata          (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                                        .readdata
		.JTAG_UART_avalon_jtag_slave_writedata         (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                                        .writedata
		.JTAG_UART_avalon_jtag_slave_waitrequest       (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                                        .waitrequest
		.JTAG_UART_avalon_jtag_slave_chipselect        (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  //                                        .chipselect
		.LDR_adc_slave_address                         (mm_interconnect_0_ldr_adc_slave_address),                   //                           LDR_adc_slave.address
		.LDR_adc_slave_write                           (mm_interconnect_0_ldr_adc_slave_write),                     //                                        .write
		.LDR_adc_slave_read                            (mm_interconnect_0_ldr_adc_slave_read),                      //                                        .read
		.LDR_adc_slave_readdata                        (mm_interconnect_0_ldr_adc_slave_readdata),                  //                                        .readdata
		.LDR_adc_slave_writedata                       (mm_interconnect_0_ldr_adc_slave_writedata),                 //                                        .writedata
		.LDR_adc_slave_waitrequest                     (mm_interconnect_0_ldr_adc_slave_waitrequest),               //                                        .waitrequest
		.Procesador1_debug_mem_slave_address           (mm_interconnect_0_procesador1_debug_mem_slave_address),     //             Procesador1_debug_mem_slave.address
		.Procesador1_debug_mem_slave_write             (mm_interconnect_0_procesador1_debug_mem_slave_write),       //                                        .write
		.Procesador1_debug_mem_slave_read              (mm_interconnect_0_procesador1_debug_mem_slave_read),        //                                        .read
		.Procesador1_debug_mem_slave_readdata          (mm_interconnect_0_procesador1_debug_mem_slave_readdata),    //                                        .readdata
		.Procesador1_debug_mem_slave_writedata         (mm_interconnect_0_procesador1_debug_mem_slave_writedata),   //                                        .writedata
		.Procesador1_debug_mem_slave_byteenable        (mm_interconnect_0_procesador1_debug_mem_slave_byteenable),  //                                        .byteenable
		.Procesador1_debug_mem_slave_waitrequest       (mm_interconnect_0_procesador1_debug_mem_slave_waitrequest), //                                        .waitrequest
		.Procesador1_debug_mem_slave_debugaccess       (mm_interconnect_0_procesador1_debug_mem_slave_debugaccess), //                                        .debugaccess
		.SRAM1_s1_address                              (mm_interconnect_0_sram1_s1_address),                        //                                SRAM1_s1.address
		.SRAM1_s1_write                                (mm_interconnect_0_sram1_s1_write),                          //                                        .write
		.SRAM1_s1_readdata                             (mm_interconnect_0_sram1_s1_readdata),                       //                                        .readdata
		.SRAM1_s1_writedata                            (mm_interconnect_0_sram1_s1_writedata),                      //                                        .writedata
		.SRAM1_s1_byteenable                           (mm_interconnect_0_sram1_s1_byteenable),                     //                                        .byteenable
		.SRAM1_s1_chipselect                           (mm_interconnect_0_sram1_s1_chipselect),                     //                                        .chipselect
		.SRAM1_s1_clken                                (mm_interconnect_0_sram1_s1_clken),                          //                                        .clken
		.TIMER_s1_address                              (mm_interconnect_0_timer_s1_address),                        //                                TIMER_s1.address
		.TIMER_s1_write                                (mm_interconnect_0_timer_s1_write),                          //                                        .write
		.TIMER_s1_readdata                             (mm_interconnect_0_timer_s1_readdata),                       //                                        .readdata
		.TIMER_s1_writedata                            (mm_interconnect_0_timer_s1_writedata),                      //                                        .writedata
		.TIMER_s1_chipselect                           (mm_interconnect_0_timer_s1_chipselect)                      //                                        .chipselect
	);

	SISTEMA_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),       // receiver1.irq
		.sender_irq    (procesador1_irq_irq)             //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                        // reset_in0.reset
		.reset_in1      (procesador1_debug_reset_request_reset), // reset_in1.reset
		.clk            (clk_clk),                               //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),        // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req),    //          .reset_req
		.reset_req_in0  (1'b0),                                  // (terminated)
		.reset_req_in1  (1'b0),                                  // (terminated)
		.reset_in2      (1'b0),                                  // (terminated)
		.reset_req_in2  (1'b0),                                  // (terminated)
		.reset_in3      (1'b0),                                  // (terminated)
		.reset_req_in3  (1'b0),                                  // (terminated)
		.reset_in4      (1'b0),                                  // (terminated)
		.reset_req_in4  (1'b0),                                  // (terminated)
		.reset_in5      (1'b0),                                  // (terminated)
		.reset_req_in5  (1'b0),                                  // (terminated)
		.reset_in6      (1'b0),                                  // (terminated)
		.reset_req_in6  (1'b0),                                  // (terminated)
		.reset_in7      (1'b0),                                  // (terminated)
		.reset_req_in7  (1'b0),                                  // (terminated)
		.reset_in8      (1'b0),                                  // (terminated)
		.reset_req_in8  (1'b0),                                  // (terminated)
		.reset_in9      (1'b0),                                  // (terminated)
		.reset_req_in9  (1'b0),                                  // (terminated)
		.reset_in10     (1'b0),                                  // (terminated)
		.reset_req_in10 (1'b0),                                  // (terminated)
		.reset_in11     (1'b0),                                  // (terminated)
		.reset_req_in11 (1'b0),                                  // (terminated)
		.reset_in12     (1'b0),                                  // (terminated)
		.reset_req_in12 (1'b0),                                  // (terminated)
		.reset_in13     (1'b0),                                  // (terminated)
		.reset_req_in13 (1'b0),                                  // (terminated)
		.reset_in14     (1'b0),                                  // (terminated)
		.reset_req_in14 (1'b0),                                  // (terminated)
		.reset_in15     (1'b0),                                  // (terminated)
		.reset_req_in15 (1'b0)                                   // (terminated)
	);

endmodule
